import "./globals.css";
import "../../css/style.css";
import "bootstrap/dist/css/bootstrap.min.css";

export const metadata = {
  title: "Reinold Chaussure",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  );
}
